font:
 normal:
   family: Iosevka Nerd Font Mono
   style: ExtraLight
 bold:
   family: Iosevka Nerd Font Mono
   style: Light
 italic:
   family: Iosevka Nerd Font Mono
   style: Light Italic
 size: 16
